version: '3'
services:
  db:
    image: mysql:latest
    container_name: test-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: test_db
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
